# These are supported funding model Python 

github: # Telebirr
patreon: # MrProfessionalHacker@outlook.com 
open_collective: # MrProfessionalHacker@outlook.com 
tidelift: # Python 
community_bridge: #  TelebirrApp
liberapay: # TelebirrApp
issuehunt: # TelebirrApp
lfx_crowdfunding: # TelebirrApp
custom: #['https://play.google.com/store/apps/details?id=cn.tydic.ethiopay&hl=en&gl=US', ['https://www.python.org/psf/sponsorship/']

