name: TelebirrApp

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    name: Release on GitHub
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: @Ethio telecom.All right reserved 1.0.0 version
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: >
            Learn more about this release from the [changelog](https://github.com/dessant/lock-threads/blob/main/CHANGELOG.md#changelog).
